function [fitresult, gof] = createFit1(xi, yi, zi)
%CREATEFIT1(XI,YI,ZI)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xi
%      Y Input : yi
%      Z Output: zi
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Aug-2022 09:12:04


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( xi, yi, zi );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'zi vs. xi, yi', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'xi', 'Interpreter', 'none' );
% ylabel( 'yi', 'Interpreter', 'none' );
% zlabel( 'zi', 'Interpreter', 'none' );
% grid on
% view( -4.6, 85.6 );


