function [fitresult, gof] = createFit(xt, yt, zt)
%CREATEFIT(XT,YT,ZT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xt
%      Y Input : yt
%      Z Output: zt
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-May-2022 09:30:46


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( xt, yt, zt );

% Set up fittype and options.
ft = 'thinplateinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'zt vs. xt, yt', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xt', 'Interpreter', 'none' );
ylabel( 'yt', 'Interpreter', 'none' );
zlabel( 'zt', 'Interpreter', 'none' );
grid on
view( -115.1, 33.7 );


