function [fitresult, gof] = Fit_First(xxb, yyb, zzb)
%CREATEFIT(XXB,YYB,ZZB)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xxb
%      Y Input : yyb
%      Z Output: zzb
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Mar-2021 18:41:26


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( xxb, yyb, zzb );

% Set up fittype and options.
ft = fittype( 'poly44' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Normalize = 'on';
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'zzb vs. xxb, yyb', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xxb', 'Interpreter', 'none' );
ylabel( 'yyb', 'Interpreter', 'none' );
zlabel( 'zzb', 'Interpreter', 'none' );
grid on
view( -49.3, 30.9 );


